# Generated by Django 3.2.5 on 2021-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battletag', models.CharField(max_length=25)),
                ('personal_sr', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=8)),
                ('lobby_sr', models.CharField(max_length=12)),
                ('replay_code', models.CharField(max_length=6)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
